config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #root to: 'devise/sessions#new'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'posts#index'
  resource :user, only: [:show, :update]
  resolve('User') { [:user] }
  
  resources :posts, only: [:new, :create, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord

    belongs_to :user

    
    validates :title, presence: true 
    validates :body, presence: true, length: { minimum: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence:true, uniqueness: true
  validates :email, presence: true, uniqueness: true 
  def email_changed?
    false 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    protected 
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password, :password_confirmation])
        devise_parameter_sanitizer.permit(:sign_in, keys: [:username, :password])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]

    def new 
        @post = Post.new 
    end 

    def create 
        @post = current_user.posts.build(post_hash) 
        if @post.save 
            redirect_to posts_path 
        else 
            render :new, status: :unprocessable_entity
        end
        
    end 

    def index 
        @posts = Post.all 
    end 

    private 
    def post_hash 
        params.require(:post).permit(:title, :body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%# manually added %>
  <% if user_signed_in? %>
    <%= link_to current_user.email, edit_user_registration_path %>
    <%= link_to "Log out", destroy_user_session_path, data: {"turbo-method": :delete } %>
  <% else %>
    <%= link_to "Log in", new_user_session_path %>
    <%= link_to "Register", new_user_registration_path %>
  <% end %>
  <%#  %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h2>Posts!</h2>
<br><br>
<%= link_to "New post", new_post_path %>
<ul>
    <% @posts.each do |post| %>
        <li>
            <h3><%= post.title %></h3>
            <p><%= post.body %></p>
            <% if user_signed_in? %>
                <p> Author: <%= post.user.username %></p>
            <% end %>
        </li>
    <% end %>
</ul>

app/views/posts/new.html.erb
<h2>Post something interesting</h2>
<br><br>
<%= form_with model: @post do |form| %>
    <%= form.label :title, 'Title: ' %>
    <%= form.text_field :title %>
    <%= form.label :body, 'Content: ' %>
    <%= form.text_field :body %>
    <%= form.submit %>
<% end %>